services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: unless-stopped
    volumes:
      - ../backend/src:/backend/src 
      - ../backend/package.json:/backend/package.json
      - /backend/node_modules
    networks:
      - dev
    depends_on:
      - mongo
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile.dev
      args:
        - GATEWAY_PORT=${GATEWAY_PORT}
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT}
      - BACKEND_URL=http://backend:${BACKEND_PORT}
    restart: unless-stopped
    ports:
      - 5921:5921
    networks:
      - dev
    volumes:
      - ../gateway/src:/gateway/src
      - ../gateway/package.json:/gateway/package.json
      - /gateway/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:8.2.2-noble
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - dev
    volumes:
      - db_data:/data/db
networks:
  dev:
    driver: bridge
volumes:
  db_data: {}
