services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - BACKEND_PORT=${BACKEND_PORT}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    depends_on:
      - mongo
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
      args:
        - GATEWAY_PORT=${GATEWAY_PORT}
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT}
      - BACKEND_URL=http://backend:${BACKEND_PORT}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    ports:
      - 5921:5921
    depends_on:
      - backend

  mongo:
    image: mongo:8.2.2-noble
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db_data:/data/db
volumes:
  db_data: {}
